# Generated by Django 6.0 on 2025-12-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_sign_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign_up',
            old_name='confirmpassword',
            new_name='confirm_password',
        ),
    ]
