# Generated by Django 6.0 on 2025-12-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_rename_confirmpassword_sign_up_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='confirm_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
