# Generated by Django 6.0 on 2025-12-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_alter_sign_up_confirm_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_up',
        ),
    ]
