# Generated by Django 6.0 on 2025-12-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_sign_up'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sign_up',
            new_name='SignUp',
        ),
    ]
