# Generated by Django 6.0 on 2025-12-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='produc_name',
        ),
    ]
