# Generated by Django 6.0 on 2025-12-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_rename_product_name_order_produc_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='produc_name',
            new_name='product_name',
        ),
    ]
