# Generated by Django 6.0 on 2025-12-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_rename_produc_name_order_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
