# Generated by Django 6.0 on 2025-12-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_mandapservice_mandapcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandapcart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
