# Generated by Django 6.0 on 2025-12-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_product_cart_delete_mandapcart_delete_mandapservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
