# Generated by Django 6.0 on 2026-01-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
