# Generated by Django 6.0 on 2026-01-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0018_cart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
