# Generated by Django 6.0 on 2026-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_cart_customer_name_alter_cart_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=10)),
                ('mno', models.IntegerField(max_length=100)),
            ],
        ),
    ]
