# Generated by Django 6.0 on 2026-01-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0020_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='img',
        ),
    ]
