# Generated by Django 6.0 on 2026-01-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0021_remove_cart_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
