# Generated by Django 6.0 on 2026-01-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0022_cart_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
