# Generated by Django 6.0 on 2026-01-18 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0025_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.productvariant')),
            ],
        ),
    ]
