# Generated by Django 6.0 on 2026-01-18 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0026_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirm', 'Confirm'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.productvariant')),
            ],
        ),
    ]
