# Generated by Django 6.0 on 2026-01-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0027_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
